site_name: 🐧 Comunidade Officinas
theme:
  name: readthedocs
  favicon: imagens/tux.ico
  logo:  imagens/logo.png
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections

extra_css:
  - extra.css
